In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding

In [4]:
text_data = [
    "The quick brown fox jumps over the lazy dog",
    "She sells sea shells by the sea shore",
    "How much wood would a woodchuck chuck if a woodchuck could chuck wood"
]

In [5]:
# Tokenization and sequence preparation (replace with your tokenizer)
tokenizer = tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(text_data)
sequences = tokenizer.texts_to_sequences(text_data)

In [6]:
# Convert sequences to input-output pairs
input_sequences = []
output_words = []
for sequence in sequences:
    for i in range(1, len(sequence)):
        input_sequence = sequence[:i]
        output_word = sequence[i]
        input_sequences.append(input_sequence)
        output_words.append(output_word)


In [7]:
# Padding sequences (optional step)
max_sequence_length = max([len(seq) for seq in input_sequences])
input_sequences = tf.keras.preprocessing.sequence.pad_sequences(input_sequences, maxlen=max_sequence_length, padding='pre')


In [8]:
# Model architecture
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=100, input_length=max_sequence_length))
model.add(LSTM(units=100))
model.add(Dense(units=len(tokenizer.word_index) + 1, activation='softmax'))


c:\Users\chhat\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [9]:
# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')

In [10]:
# Train the model (replace with your training data)
model.fit(input_sequences, output_words, epochs=50, batch_size=32)

ValueError: Unrecognized data type: x=[[ 0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  1  7]
 [ 0  0  0  0  0  0  0  0  0  1  7  8]
 [ 0  0  0  0  0  0  0  0  1  7  8  9]
 [ 0  0  0  0  0  0  0  1  7  8  9 10]
 [ 0  0  0  0  0  0  1  7  8  9 10 11]
 [ 0  0  0  0  0  1  7  8  9 10 11  1]
 [ 0  0  0  0  1  7  8  9 10 11  1 12]
 [ 0  0  0  0  0  0  0  0  0  0  0 14]
 [ 0  0  0  0  0  0  0  0  0  0 14 15]
 [ 0  0  0  0  0  0  0  0  0 14 15  2]
 [ 0  0  0  0  0  0  0  0 14 15  2 16]
 [ 0  0  0  0  0  0  0 14 15  2 16 17]
 [ 0  0  0  0  0  0 14 15  2 16 17  1]
 [ 0  0  0  0  0 14 15  2 16 17  1  2]
 [ 0  0  0  0  0  0  0  0  0  0  0 19]
 [ 0  0  0  0  0  0  0  0  0  0 19 20]
 [ 0  0  0  0  0  0  0  0  0 19 20  3]
 [ 0  0  0  0  0  0  0  0 19 20  3 21]
 [ 0  0  0  0  0  0  0 19 20  3 21  4]
 [ 0  0  0  0  0  0 19 20  3 21  4  5]
 [ 0  0  0  0  0 19 20  3 21  4  5  6]
 [ 0  0  0  0 19 20  3 21  4  5  6 22]
 [ 0  0  0 19 20  3 21  4  5  6 22  4]
 [ 0  0 19 20  3 21  4  5  6 22  4  5]
 [ 0 19 20  3 21  4  5  6 22  4  5 23]
 [19 20  3 21  4  5  6 22  4  5 23  6]] (of type <class 'numpy.ndarray'>)

In [ ]:
# Predict next words based on user input
user_input = "The quick"
user_sequence = tokenizer.texts_to_sequences([user_input])[0]
predicted_sequence = model.predict_classes(tf.expand_dims(user_sequence, axis=0), verbose=0)


In [ ]:
# Decode predicted sequence to words
predicted_word = tokenizer.index_word[predicted_sequence[0]]
print(f"Predicted next word: {predicted_word}")